services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\SearchBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Controller services.
    Bkstg\SearchBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Block services.
    Bkstg\SearchBundle\Block\:
        resource: '../../Block'
        public: true
        arguments:
            - null
        tags:
            - { name: sonata.block }

    # Finder service alias for autowiring.
    FOS\ElasticaBundle\Finder\FinderInterface: '@fos_elastica.finder.app'

    # Event listener
    Bkstg\SearchBundle\EventListener\SearchBar:
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.bkstg.search_bar, method: onBlock }
    Bkstg\SearchBundle\EventListener\SearchFields:
        tags:
            - { name: kernel.event_listener, event: bkstg_search.field_collection, method: addFields }
