services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\SearchBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Controller services.
    Bkstg\SearchBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Block services.
    Bkstg\SearchBundle\Block\:
        resource: '../../Block'
        public: true
        arguments:
            - null
            - '@sonata.templating'
        tags:
            - { name: sonata.block }

    # Doctrine event listeners.
    Bkstg\SearchBundle\EventListener\SearchIndexListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
    # Event listener
    Bkstg\SearchBundle\EventListener\SearchBar:
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.bkstg.search.search_bar, method: onBlock }
    Bkstg\SearchBundle\EventListener\SearchFields:
        tags:
            - { name: kernel.event_listener, event: bkstg_search.field_collection, method: addFields }

    # Autowiring.
    Bkstg\SearchBundle\Metadata\MetadataManagerInterface: '@Bkstg\SearchBundle\Metadata\MetadataManager'
